project:
  type: website
  render: 
    - index.qmd
    - Install_software.qmd
    - slides/slides_1.qmd
website:
  title: "inlabru_NewCaledonia"
  navbar:
    logo: Image/INLA_logo.png
    right:
      - text: "Home"
        href: index.qmd
    left:
      - text: "Slides"
        menu:
          - text: "Slides 1"
            href: slides/slides_1.qmd
format:
  revealjs:
    footer: "<a href='../index.html'>Back to Home</a>"
        
publish:
  gh-pages:
    branch: gh-pages


