project:
  type: website
  render: 
    - index.qmd
    - Install_software.qmd
    - slides/slides_1.qmd
    - practicals/LMM_ex.qmd
website:
  title: "inlabru_NewCaledonia"
  navbar:
    logo: Image/INLA_logo.png
    right:
      - text: "Home"
        href: index.qmd
    left:
      - text: "Installation"
        href: Install_software.qmd
      - text: "Slides"
        menu:
          - text: "Slides 1 - Introduction"
            href: slides/slides_1.qmd
      - text: "Practicals"
        menu:
          - text: "Practical 1 - Fit LMM"
            href: practicals/LMM_ex.qmd

format:
  revealjs:
    footer: "<a href='../index.html'>Back to Home</a>"
        
publish:
  gh-pages:
    branch: gh-pages
execute:
  freeze: auto

